
### Register
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "name": "Ruhit Hassan",
  "username": "ruhithassan",
  "password": "12345678"
}

### Login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "username": "ruhithassan",
  "password": "12345678"
}
